name: Request Multiple URLs and Fetch Responses

on:
  workflow_dispatch: # Permite acionar manualmente

jobs:
  request-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Request Multiple URLs
      env:
        URLS: "google.com" # Substitua com as URLs necessárias
      run: |
        for url in $URLS; do
          echo "Requesting URL: $url"
          # Limite de tempo de 5 segundos e tamanho de resposta de 50 KB, com codificação UTF-8
          response=$(curl -k -s --max-time 5 --max-filesize 50000 -H "Accept-Charset: UTF-8" $url)
          # Força a codificação para UTF-8 e ignora caracteres inválidos
          echo "Response from $url: $(echo "$response" | iconv -f UTF-8 -t UTF-8 -c)"
        done
